# Generated by Django 5.0.6 on 2024-05-28 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='email_verify',
            field=models.BooleanField(default=False),
        ),
    ]
