# Generated by Django 5.0.6 on 2024-05-18 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='subscription',
            field=models.CharField(default='Non', max_length=6),
        ),
    ]
