# Generated by Django 5.0.6 on 2024-05-23 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_app', '0002_alter_users_subscription'),
    ]

    operations = [
        migrations.CreateModel(
            name='Users_info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.DeleteModel(
            name='Users',
        ),
    ]
