# Generated by Django 5.0.6 on 2024-05-26 23:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login_app', '0004_users'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Users_info',
        ),
    ]
